#!/bin/bash

path_add() {
    if [ -d "$1" ] && [[ ! $PATH =~ (^|:)$1(:|$) ]];
    then
        PATH+=:$1
    fi
}

path_add /home/matt/bin
path_add /home/matt/opt/sbt
path_add /home/matt/opt/idea/latest/bin
path_add /home/matt/opt/node/latest/bin

alias l='ls -1'
alias la="ls -la"

alias ..="cd .."

alias emacs-daemon="emacs --daemon"
alias e-d="emacs --daemon"
alias emacs-kill="emacsclient -eval \"(kill-emacs)\""
alias e-k="emacsclient -eval \"(kill-emacs)\""
alias e="emacsclient -n"
