#!/bin/bash

path_add() {
    if [ -d "$1" ] && [[ ! $PATH =~ (^|:)$1(:|$) ]];
    then
        PATH+=:$1
    fi
}

path_add /home/matt/bin
path_add /home/matt/opt/sbt
path_add /home/matt/opt/idea/latest/bin
path_add /home/matt/opt/node/latest/bin

function bash-reload () {
    . ~/.bash_aliases
}

# rm alternative
function mvt () {
    if [[ -f $1 ]] || [[ -d $1 ]]
    then
        mv $1 ~/tmp/`date +%Y%m%d-%H%M%S`-`basename $1`
    else
        echo "mvt: missing file operand"
    fi
}

alias l='ls -1'
alias la="ls -la"

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

alias agi="sudo apt-get install"
alias acs="apt-cache show"
alias acr="apt-cache search"

alias json="python -mjson.tool"

alias emacs-daemon="emacs --daemon"
alias e-d="emacs --daemon"
alias emacs-kill="emacsclient -eval \"(kill-emacs)\""
alias e-k="emacsclient -eval \"(kill-emacs)\""
alias e="emacsclient -n"
