#!/bin/sh

path_add() {
    if [ -d "$1" ] && [[ ! $PATH =~ (^|:)$1(:|$) ]]; then
        PATH+=:$1
    fi
}

path_add /home/matt/bin
path_add /home/matt/opt/sbt
path_add /home/matt/opt/idea/latest/bin
path_add /home/matt/opt/node/latest/bin

alias l='ls -1'
alias la="ls -la"

alias ..="cd .."

alias emacs-daemon="emacs --daemon"
alias e="emacsclient -n"
